# Generated by Django 5.2.3 on 2025-06-18 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile', models.ImageField(upload_to='profile_pics/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10)),
            ],
        ),
    ]
